"""
app/models/submission.py
Submission — one row per field observation submitted by a cadre.

Status lifecycle:
    PENDING → PROCESSING → VERIFIED
                         → REJECTED
"""
from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    DateTime,
    Enum as SAEnum,
    Float,
    ForeignKey,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class SubmissionStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    VERIFIED = "verified"
    REJECTED = "rejected"


# Observation type → human label mapping (canonical list, authoritative backend definition)
OBSERVATION_TYPE_LABELS: dict[str, str] = {
    "water_body": "Water Body",
    "check_dam": "Check Dam",
    "farm_pond": "Farm Pond",
    "contour_trench": "Contour Trench",
    "gully_plug": "Gully Plug",
    "percolation_tank": "Percolation Tank",
    "groundwater": "Groundwater",
    "borewell": "Borewell",
    "well": "Open Well",
    "irrigation": "Irrigation",
    "water_quality": "Water Quality",
    "other": "Other",
}

# Reward schedule INR per verified observation (canonical policy — see earnings_policy.py)
REWARD_SCHEDULE: dict[str, int] = {
    "water_body": 25,
    "check_dam": 20,
    "farm_pond": 25,
    "contour_trench": 20,
    "gully_plug": 15,
    "percolation_tank": 25,
    "groundwater": 20,
    "borewell": 20,
    "well": 20,
    "irrigation": 20,
    "water_quality": 25,
    "other": 15,
}


class Submission(Base):
    __tablename__ = "submissions"

    # Primary key — GW-XXXXXX format generated by id_generator
    id: Mapped[str] = mapped_column(String(20), primary_key=True)

    # Foreign key → CadreProfile
    cadre_id: Mapped[str] = mapped_column(
        String, ForeignKey("cadre_profiles.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Observation metadata
    observation_type: Mapped[str] = mapped_column(String(40), nullable=False)
    type_label: Mapped[str | None] = mapped_column(String(80), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    channel: Mapped[str] = mapped_column(String(20), default="web", nullable=False)

    # Location
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    location_label: Mapped[str | None] = mapped_column(String(200), nullable=True)

    # Photo storage
    photo_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    photo_filename: Mapped[str | None] = mapped_column(String(200), nullable=True)

    # Capture time (when the photo was taken, as sent by client)
    capture_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Status
    status: Mapped[SubmissionStatus] = mapped_column(
        SAEnum(SubmissionStatus, name="submission_status", create_constraint=True),
        default=SubmissionStatus.PENDING,
        nullable=False,
        index=True,
    )

    # Verification results (filled by AI/satellite engines — Phase 6+)
    ai_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    satellite_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    final_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    verified_by: Mapped[str | None] = mapped_column(String(80), nullable=True)
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now(), nullable=True
    )

    # Relationships
    cadre: Mapped["CadreProfile"] = relationship(  # noqa: F821
        "CadreProfile", back_populates="submissions"
    )
    earnings_record: Mapped["EarningsLedger | None"] = relationship(  # noqa: F821
        "EarningsLedger", back_populates="submission", uselist=False
    )
    verification_events: Mapped[list["VerificationEvent"]] = relationship(  # noqa: F821
        "VerificationEvent", back_populates="submission", cascade="all, delete-orphan"
    )

    @property
    def reward_amount(self) -> int:
        """Expected reward for this observation type (INR)."""
        return REWARD_SCHEDULE.get(self.observation_type, 15)

    def __repr__(self) -> str:
        return f"<Submission id={self.id!r} type={self.observation_type!r} status={self.status!r}>"
